### ISSUE TITLE
Padding and Margin to "HOME" and "Search" should look nice

### ISSUE THREAD

**Issue by tushar-rishav** [delta/Website-NITT-2016#11]
Adding 
```css
.search-icon{
margin: 1%;
}
.breadcrumb{
padding: 5px 0 0 12px; 
/* Presently it's  5px 0 0 0 .
Adding a padding left side would look nice. Otherwise "HOME" looks sticky to the left wall. */
}
```
Before
![padding](https://cloud.githubusercontent.com/assets/7397433/14942382/017b0f94-0fd9-11e6-9800-e696e94e269f.png)

After
![nice](https://cloud.githubusercontent.com/assets/7397433/14942383/05f5a732-0fd9-11e6-9c5a-aeacd042fa13.png)
